add Min-K%++ attack
iamgroot42/mimir pull request #19
Opened 2024-04-04 15:03 UTC by zjysteven

Hi @iamgroot42, first thanks for putting up this unified benchmark. 

## Overview
This pull request add our proposed method, Min-K%++, which outperforms other reference-free methods and performs on par with the Ref method on MIMIR. See below experiment part for details.

## Changed files
We follow the instruction to create `attacks/mink_plus_plus.py` and register the method in `attacks/all_attacks.py` and `attacks/utils.py`. Our method needs the full probabilities over the vocabulary, so we modify the `get_probabilities` function in `models.py` with an additional argument `return_all_probs` to return full probs.

Meanwhile, we change `run.py` accordingly to include our Min-K%++ attack. Additionally, we let both Min-K% and Min-K%++ to run over a list of `k` values, which allows both methods to be compared by their upper bounds.

Lastly, we change the readme to incorporate Min-K%++.

## Experiments
![image](https://github.com/iamgroot42/mimir/assets/19763611/f328840a-0bea-415e-850f-b656fbe73e72)
I'm putting this result table here in case MIMIR wants to have a leaderboard or something. We are using non-deduped pythia models and the default `ngram_13_0.8` setting. The data splits are fetched from `cache_100_200_1000_512` folder on huggingface.

Let us know if there are any issues. Otherwise, we look forward to Min-K%++ being integrated into the MIMIR benchmark.

2024-04-04 15:15 UTC, iamgroot42 commented
Thanks a lot for the PR, @zjysteven ! I have a couple suggestions that I have added via comments. The fact that you submitted such a well-structured PR is alone sufficient and I would understand if you would rather have us make these changes, but would be great if you could make those changes

2024-04-04 15:21 UTC, zjysteven commented
Yes I can make further changes. Somehow I'm not seeing your comments. Would you please point me to the comments?

2024-04-04 15:22 UTC, iamgroot42 requested changes

2024-04-04 15:22 UTC, iamgroot42 commented on mimir/attacks/min_k_plus_plus.py
> +            else self.model.get_probabilities(document, tokens=tokens, return_all_probs=True)
Is there a reason for computing softmax and log_softmax separately? Given access to the latter (which is default right now), a exp() operation should give you the desired softmax outputs for use in mink++?

2024-04-04 15:22 UTC, iamgroot42 commented on run.py
> +                        if attack in [AllAttacks.MIN_K, AllAttacks.MIN_K_PLUS_PLUS]:
Our intent with the structure was to have as few attack-specific checks as possible. We plan on adding attack-specific hyper-parameters in the config file, so that any changes required for the attack here can be achieved by different config files, and not hard-coded hyper-parameters and switch-case in code!

2024-04-04 15:29 UTC, zjysteven commented on mimir/attacks/min_k_plus_plus.py
> +            else self.model.get_probabilities(document, tokens=tokens, return_all_probs=True)
I see. Earlier I misread and thought that we have softmax, and since log_softmax is numerically more stable than log(softmax) I compute them separately (but yeah as you pointed what we have already is log_softmax). I will change this so the forward pass of the model (`get_probabilites`) will be kept as-is.

2024-04-04 15:30 UTC, zjysteven commented on run.py
> +                        if attack in [AllAttacks.MIN_K, AllAttacks.MIN_K_PLUS_PLUS]:
Also a valid point. I will just remove this modification so `run.py` follows the current design.

2024-04-04 15:53 UTC, zjysteven commented on mimir/attacks/min_k_plus_plus.py
> +            else self.model.get_probabilities(document, tokens=tokens, return_all_probs=True)
I do want to clarify here that while `target_prob` is the log probability of each input token, `all_prob` is the log probabilities of every token in the vocabulary (the whole categorical distribution).

2024-04-04 15:54 UTC, zjysteven commented
I've made changes accordingly in the latest commit. Would you take another look?

2024-04-04 15:55 UTC, zjysteven commented on mimir/models.py
> -                probabilities = torch.nn.functional.softmax(shift_logits, dim=-1)
Like suggested here we don't need to separately call `softmax` given that `log_softmax` will be computed anyway.

2024-04-05 18:56 UTC, iamgroot42 commented
Thanks for making the changes! Will run our standard workflow and merge it

2024-04-05 18:57 UTC, iamgroot42 approved these changes

2024-04-05 19:03 UTC, merged